[tool.poetry]
name = "auto-doco"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31"
click = "^8.1"
mkdocs = ">=1.6.1,<2.0.0"
mkdocs-material = ">=9.7.2,<10.0.0"
python-dotenv = ">=1.2.1,<2.0.0"

[tool.poetry.scripts]
collect = "auto_doco.cli:run"